### ISSUE TITLE
Hotkeys don't work

### ISSUE THREAD

**Issue by SeLiEnisyst** [FabianUntermoser/obsidian-neighbouring-files-plugin#11]
Hi,

I tried following two hotkeys:

Strg + Alt + Shift + arrow up
Alt + arrow down

... and both didn't work.

Furthermore the plugin doesn't show up in the list of installed community plugins on the left side of the first settings-page.

If needed, here es my debug info:
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.11
	Operating system: Windows 10 Pro 10.0.22631
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.2
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 46
	Plugins enabled: 24
		1: Templater v2.2.3
		2: Excalidraw v2.1.4
		3: Hotkeys for templates v1.4.3
		4: Hotkeys++ v0.2.7
		5: Minimal Theme Settings v7.5.0
		6: Strange New Worlds v2.1.0
		7: Periodic Notes v0.0.17
		8: Style Settings v1.0.8
		9: Tag Wrangler v0.6.1
		10: Underline v1.3.0
		11: Quick Latex v2.6.5
		12: Dataview v0.5.66
		13: Vantage - Advanced search builder v1.4.2
		14: MSG Handler v0.0.6
		15: Emoji Toolbar v0.4.1
		16: Excel to Markdown Table v0.4.0
		17: Tasks v7.0.0
		18: Recent Files v1.3.10
		19: markdown export v1.0.20
		20: Commander v0.5.1
		21: Whisper v1.5.5
		22: File Color v1.1.0
		23: Media Extended v3.1.0
		24: Neighbouring Files v1.0.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by FabianUntermoser** [comment]
Hi,
have you checked these shortcuts are not used by other plugins?
Both of the shortcuts you mentioned work for me.
Could you also try other shortcuts and report back?

And the reason why this plugin does not show up on the left hand side in the settings panel is because it does not provide any other configuration than shortcuts.
