### ISSUE TITLE
Plugin creates markdown files for folders

### ISSUE THREAD

**Issue by clemens-holleis** [FabianUntermoser/obsidian-neighbouring-files-plugin#2]
# reproduce unexpected behaviour in fresh vault

1. install Addon and activate
2. create a file named `File 01`
3. create a folder `Folder 01`
4. view `File 01` in Obsidian
5. trigger `Neighbouring Files: Navigate to next file` command
6. 💥**now the addon creates a new markdown file named `Folder 01`**

I think the Folders should be simply ignored, right?

kind regards,
Clemens

**Comment by clemens-holleis** [comment]
I fixed that by adding a filter to the files list and created a pull request:
https://github.com/FabianUntermoser/obsidian-neighbouring-files-plugin/pull/3

**Comment by FabianUntermoser** [comment]
Thanks for your contribution! I did not consider other files being present in the same directory.

Also, I left you a comment in your PR.
