### ISSUE TITLE
latest build can not be installed

### ISSUE THREAD

**Issue by clemens-holleis** [FabianUntermoser/obsidian-neighbouring-files-plugin#5]
the current build (version 1.0.4) can not be installed.

- install / update starts
- getting message `Failed to install plugin "Neighbouring Files".`

**Comment by FabianUntermoser** [comment]
Issue resolved by including manifest.json in [Release 1.0.4](https://github.com/FabianUntermoser/obsidian-neighbouring-files-plugin/releases/tag/1.0.4).
