### ISSUE TITLE
Note switching breaks when using a "Johnny Decimal" strucutre for notes

### ISSUE THREAD

**Issue by ryanwoong** [FabianUntermoser/obsidian-neighbouring-files-plugin#6]
When you are in a note such as 2.1 and have notes going from 2.2, 2.3, ... 2.23 the switcher will automatically jump from 2.1 to 2.10 skipping the notes from 2.2 to 2.9.

**Comment by FabianUntermoser** [comment]
Thanks for letting me know. 
Took quite a bit of fiddling to this simple fix.

Fixed in [Release 1.0.6](https://github.com/FabianUntermoser/obsidian-neighbouring-files-plugin/releases/tag/1.0.6)
