### ISSUE TITLE
Move through files in case-insensitive order

### ISSUE THREAD

**Issue by dreadnaut** [FabianUntermoser/obsidian-neighbouring-files-plugin#7]
While the Obsidian file tree sorts entries without considering case (* at least on Windows, haven't tested other platforms), Neighbouring Files moves through them in case-sensitive order. For example, Obsidian will display my test files ignoring the case of the first letter:

![image](https://github.com/FabianUntermoser/obsidian-neighbouring-files-plugin/assets/584584/d31c25c3-728a-402f-8248-c15836649da2)

but the "Navigate to next file" command will move through `1` → `2` → `4` → `3`.

I would expect the plugin to move through files in the order they appear in Obsidian file tree, that is, `1` → `2` → `3` → `4`.

**Comment by FabianUntermoser** [comment]
Thanks for posting.

Fixed in [Release 1.0.5](https://github.com/FabianUntermoser/obsidian-neighbouring-files-plugin/releases/tag/1.0.5)

**Comment by dreadnaut** [comment]
Thank you for the prompt fix!
